#!/bin/sh
########################################################################
# Begin lxdm
#
# Description :
#
# Authors     : Scott Court (Z5T1@Z5T1.com)
#
# Version     : Cucumber 1.0
#
########################################################################

### BEGIN SYMLINK INFO
# This section controls the name of the symlinks that are created in
# /etc/rc.d/rc?.d by chkconfig and the system init setup script.
# START_LINK_NAME       S95lxdm
# KILL_LINK_NAME        K05lxdm
### END SYMLINK INFO

### BEGIN INIT INFO
# Provides:             lxdm
# Default-Start: 5
# Default-Stop: 0 1 2 3 4 6
### END INIT INFO


. /lib/lsb/init-functions

BIN_FILE="/usr/sbin/lxdm"

#$LastChangedBy: ken $
#$Date: 2014-09-11 22:27:58 +0000 (Thu, 11 Sep 2014) $

case $1 in
   start)
	log_info_msg "Starting LXDM..."
	start_daemon $BIN_FILE -d
	evaluate_retval
	;;

   stop)
	log_info_msg "Stopping LXDM..."
 	killproc $BIN_FILE
	evaluate_retval
	;;

   restart)
	$0 stop
	sleep 2
	$0 start
	;;

   status)
        statusproc ${BIN_FILE}
        ;;

   *)
	echo "usage: $0 [start|stop|restart|status]"
        exit 1
	;;
esac

# End /etc/rc.d/init.d/lxdm
