#!/bin/bash

iface_up () {
	# Configure the interface
	ifconfig $INTERFACE up
	iwconfig $INTERFACE essid "$WIRELESS_SSID"

	# Chainloading
	if [ ! -z $WIRELESS_CHAINLOAD ]; then
		. /etc/network/methods/${WIRELESS_CHAINLOAD} up
	fi
}

iface_down () {
	# Chainloading
	if [ ! -z $WIRELESS_CHAINLOAD ]; then
		. /etc/network/methods/${WIRELESS_CHAINLOAD} down
	fi

	ifconfig $INTERFACE down
}

iface_help () {
	cat << EOF
Wireless Configuration Help

This configuration method configures a wireless network interface to connect to
an unsecured network. 

This method does not handle the addressing portion of the configuration. For
this reason, an additional network configuration method may be chainloaded. 
See the templates in /etc/network/templates for an example of how to do this.

This configuration method permits the following optional fields in the
configuration file: 
WIRELESS_SSID        The SSID of the network to connect to. To scan for a list 
                     of available networks, use 'iwlist <interface> scan'.
WIRELESS_CHAINLOAD   An additional configuration method to chainload after
                     connecting to the network.

See /etc/network/templates/ for wireless configuration templates.
EOF
}

case $1 in
	"up")
		iface_up
		;;
	"down")
		iface_down
		;;
	"help")
		iface_help
		;;
	*)
		echo "Usage: $1 <up|down|help>"
		exit 1
esac
